### PR TITLE
Add bower dependencies images to globs

### PR DESCRIPTION
**Pull request by alexandcote**
Here is the issue https://github.com/austinpray/asset-builder/issues/33

### CODE REVIEW

**Comment by austinpray** [comment]
Oh nice!! 

Would you mind adding some tests to cover images being pulled in from a bower package?

**Comment by alexandcote** [comment]
Yes I could but I would like your opinion on this. After testing with bxslider, it seems like the CSS files don’t get the images on the right place. Do you know what might cause this or how to fix this glitch?

**Comment by austinpray** [comment]
Hmm let's ask the dude that maintains bxslider:

Yo Eric (@Tidal-Wave): what do you do about bxslider and images as it related to bower? 

As far as my thinking:
just override the CSS in your own CSS file like so:

```css
.bx-wrapper .bx-loading {
	background: url(../path/to/images/bx_loader.gif) center center no-repeat #fff;
}
```

CSS Cascades so your changes should override bxslider's as the specificity is higher.

**Comment by Tidal-Wave** [comment]
Generally speaking the second is what I do but minus the `!important`, I usually import the less file for bxSlider before my main file. I'm open to change if need be. Im in the middle of an update to it so nows the time for suggestions.

**Comment by austinpray** [comment]
@Tidal-Wave should be as simple as just making the images path a variable that is configurable, right?

Does less have a !default equivalent? http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_

**Comment by Tidal-Wave** [comment]
Not really because they Lazy Load, [so you just override it after the import statement](http://lesscss.org/features/#variables-feature-default-variables).
I can switch to using a variable, that should be fine, I just wrote that LESS file on the quick from the original css. Do you need now or can I push it in a day or two with 4.2.4?

**Comment by alexandcote** [comment]
@Tidal-Wave It would be interesting to have a variable for the path of the images. In this way, it would be easy to replace the value of the path. Thanks a lot for your helps guys

**Comment by austinpray** [comment]
@Tidal-Wave no rush here :sunglasses:

**Comment by alexandcote** [comment]
Ahahah I can wait 4.2.4 :satisfied:

**Comment by alexandcote** [comment]
@austinpray Feel free to comment, I'm open to make changes.

**Comment by austinpray** [comment]
looks good to me!

**Comment by austinpray** [comment]
released as 1.1.0

**Pull request merged**
