### PR TITLE
Adds windoze compatibility

### PR DESCRIPTION
**Pull request by austinpray**
https://github.com/roots/sage/issues/1351

### CODE REVIEW

**Comment by austinpray** [comment]
thanks @coveralls

**Comment by QWp6t** [comment]
@coveralls can we get another update on the coverage? I would like to know if it has changed within the last 8 minutes.

**Comment by austinpray** [comment]
I would like to thank @coveralls and Obama for this patch

**Comment by JulienMelissas** [comment]
lol u guyz

**Comment by JulienMelissas** [comment]
Obama needs a github profile

**Pull request merged**
