### PR TITLE
Fixed issue #47

### PR DESCRIPTION
**Pull request by CapacitorSet**
- `/Users/austinpray/DEV/opensauce/asset-builder/test/tmp/bower_components/bootstrap` -> `/Bootstrap`

`/Users/austinpray/DEV/opensauce/asset-builder/test/tmp/bower_components/jquery` -> `/Jquery`

### CODE REVIEW

**Comment by austinpray** [comment]
Hey @CapacitorSet! 

Thanks for the PR. This breaks the tests however.

Instead of `/Jquery/dist/jquery.js` it should be `/asset-builder/bower_components/jquery/dist/jquery.js`

**Comment by CapacitorSet** [comment]
Thanks for the tip, I'll fix it in a few hours when I'm home again. I
noticed the bounty and pushed a quick fix, but didn't have time to inspect
the tests to see what was wrong.
Il 04/ago/2015 19:46, "Austin Pray" <notifications@github.com> ha scritto:

**Comment by austinpray** [comment]
@CapacitorSet also go ahead and rebase against the latest master to fix an issue with jscs in the CI

**Comment by CapacitorSet** [comment]
@austinpray Fixed.

**Comment by CapacitorSet** [comment]
Whoops, closed by accident

**Comment by austinpray** [comment]
Sweet! Looks good to go. Let's just rebase the commits into one commit

```bash
git rebase -i HEAD~4
```

Which then gives you

```
pick 29b60b1 ignore help directory in npm package
pick f1881f6 Fixed issue austinpray/asser-builder#47
pick 3dc6142 JSCS fixes
pick d4f1500 1.1.1
pick 32936fa Fixed as per request
```

Make it look like

```
pick 29b60b1 ignore help directory in npm package
pick 3dc6142 JSCS fixes
pick d4f1500 1.1.1
pick f1881f6 Fixed issue austinpray/asser-builder#47
s 32936fa Fixed as per request
```

Then we will have everything nice and tidy:

image

`git push -f` to update your branch

**Comment by CapacitorSet** [comment]
Uh, I think I screwed up the commit messages, but it worked.

**Comment by austinpray** [comment]
Thanks man!

**Pull request merged**
