### PR TITLE
Fixed one high vulnerability introduced due to a dependency `object-path`

### PR DESCRIPTION
**Pull request by vinayjeurkarzymr**
- Fixed one high vulnerability introduced due to a dependency `object-path`
- Gone through the code to verify that the breaking changes stated here at : https://www.npmjs.com/package/object-path are not affecting asset-builder code.

### CODE REVIEW

**Comment by vinayjeurkarzymr** [comment]
@mmirus Can you look into this PR and merge. 

Thank you In Advance.

**Review by austinpray — APPROVED** [review]

**Comment by austinpray** [comment]
Thank you! Will make a release soon

**Comment by vinayjeurkarzymr** [comment]
@austinpray
Thank you.

**Comment by vinayjeurkarzymr** [comment]
@austinpray @mmirus 
Can you create a release that includes this fix.
Thanks in advance.

**Comment by vinayjeurkarzymr** [comment]
@austinpray @mmirus 
Just want to pass a silent reminder. If you can create a release that includes this change, then that would be great.
Thanks in Advance.

**Comment by vijayhardaha** [comment]
@austinpray Looking for a new release. Thanks
@vinayjeurkarzymr If possible can you add the default option `useBower: true` to keep bower optional in use and then make Manifest like this.

```js
var Manifest = module.exports = function(path, options) {
  var manifest = processManifest(readManifest(path));
  var bower = manifest.useBower ? mainBowerFiles(_.pick(options, [
    'paths'
  ])) : [];
  this.config = manifest.config;
  this.dependencies = manifest.dependencies;
  this.globs = new BuildGlobs(manifest.dependencies, bower, options).globs;
  this.paths = manifest.paths;
};
```

In most of the projects I don't use bower but I have to create `bower.json` and `bower_components` folder in order to use this package. Will be nice to keep bower optional.

**Pull request merged**
